version: 2

project_name: bb

builds:
  - id: bb
    main: ./cmd/bb
    binary: bb
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X bb-project/internal/cli.buildVersion={{ .Version }} -X bb-project/internal/cli.buildCommit={{ .Commit }} -X bb-project/internal/cli.buildDate={{ .Date }}

archives:
  - id: bb
    ids:
      - bb
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

release:
  draft: false

brews:
  - repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    description: "CLI to keep Git repositories consistent across machines."
    test: |
      system "#{bin}/bb", "version"
    install: |
      bin.install "bb"
    commit_author:
      name: bb release bot
      email: actions@users.noreply.github.com
