.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-catalog-list - List configured catalogs and mark default.


.SH SYNOPSIS
\fBbb catalog list [flags]\fP


.SH DESCRIPTION
List configured catalogs and mark default.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-catalog(1)\fP
