.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-catalog - Manage machine catalogs and default catalog selection.


.SH SYNOPSIS
\fBbb catalog [flags]\fP


.SH DESCRIPTION
Manage machine catalogs and default catalog selection.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for catalog


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP, \fBbb-catalog-add(1)\fP, \fBbb-catalog-default(1)\fP, \fBbb-catalog-list(1)\fP, \fBbb-catalog-rm(1)\fP
