.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-catalog-rm - Remove catalog from current machine.


.SH SYNOPSIS
\fBbb catalog rm  [flags]\fP


.SH DESCRIPTION
Remove catalog from current machine.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for rm


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-catalog(1)\fP
