.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-catalog-add - Add catalog root to current machine.


.SH SYNOPSIS
\fBbb catalog add   [flags]\fP


.SH DESCRIPTION
Add catalog root to current machine.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for add


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-catalog(1)\fP
