.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-catalog-default - Set machine default catalog.


.SH SYNOPSIS
\fBbb catalog default  [flags]\fP


.SH DESCRIPTION
Set machine default catalog.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for default


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-catalog(1)\fP
