.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-doctor - Report unsyncable repositories and reasons.


.SH SYNOPSIS
\fBbb doctor [flags]\fP


.SH DESCRIPTION
Report unsyncable repositories and reasons.

.PP
When GitHub integration is configured (or selected repositories use GitHub remotes),
doctor also checks GitHub CLI prerequisites and emits warnings when gh is missing
or unauthenticated, including remediation guidance.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for doctor

.PP
\fB--include-catalog\fP=[]
	Limit scope to selected catalogs (repeatable).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP
