.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-diff - Launch Lumen visual diff in repository context.


.SH SYNOPSIS
\fBbb diff  ...args [flags]\fP


.SH DESCRIPTION
Launch Lumen visual diff in repository context.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for diff


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP
