.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-ensure - Alias for sync convergence over selected catalogs.


.SH SYNOPSIS
\fBbb ensure [flags]\fP


.SH DESCRIPTION
Alias for sync convergence over selected catalogs.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for ensure

.PP
\fB--include-catalog\fP=[]
	Limit scope to selected catalogs (repeatable).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP
