.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-info - Show resolved local project information.


.SH SYNOPSIS
\fBbb info  [flags]\fP


.SH DESCRIPTION
Show resolved local project information.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for info


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP
