.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-repo-remote - Set repository preferred remote for sync/fix operations.


.SH SYNOPSIS
\fBbb repo remote  [flags]\fP


.SH DESCRIPTION
Set repository preferred remote for sync/fix operations.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for remote

.PP
\fB--preferred-remote\fP=""
	Preferred remote name for this repository (for example origin or upstream).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-repo(1)\fP
