.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-repo-access-set - Set cached repository push access (read_write|read_only|unknown).


.SH SYNOPSIS
\fBbb repo access-set  [flags]\fP


.SH DESCRIPTION
Set cached repository push access (read_write|read_only|unknown).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for access-set

.PP
\fB--push-access\fP=""
	Cached push access level (read_write|read_only|unknown).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-repo(1)\fP
