.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-repo-access-refresh - Probe and refresh cached repository push access.


.SH SYNOPSIS
\fBbb repo access-refresh  [flags]\fP


.SH DESCRIPTION
Probe and refresh cached repository push access.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for access-refresh


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-repo(1)\fP
