.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-repo - Manage repository metadata and policy settings.


.SH SYNOPSIS
\fBbb repo [flags]\fP


.SH DESCRIPTION
Manage repository metadata and policy settings.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for repo


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP, \fBbb-repo-policy(1)\fP
