.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-repo-policy - Set repository auto-push policy.


.SH SYNOPSIS
\fBbb repo policy  [flags]\fP


.SH DESCRIPTION
Set repository auto-push policy.


.SH OPTIONS
\fB--auto-push\fP=""
	Set auto-push mode (false|true|include-default-branch).

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for policy


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-repo(1)\fP
