.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-scan - Discover repositories under catalogs and publish machine state.


.SH SYNOPSIS
\fBbb scan [flags]\fP


.SH DESCRIPTION
Discover repositories under catalogs and publish machine state.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for scan

.PP
\fB--include-catalog\fP=[]
	Limit scope to selected catalogs (repeatable).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP
