.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-scheduler - Manage periodic sync scheduler integration.


.SH SYNOPSIS
\fBbb scheduler [flags]\fP


.SH DESCRIPTION
Manage periodic sync scheduler integration.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for scheduler


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP, \fBbb-scheduler-install(1)\fP, \fBbb-scheduler-remove(1)\fP, \fBbb-scheduler-status(1)\fP
