.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-scheduler-install - Install or update periodic scheduler job for bb sync.


.SH SYNOPSIS
\fBbb scheduler install [flags]\fP


.SH DESCRIPTION
Install or update periodic scheduler job for bb sync.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for install

.PP
\fB--notify-backend\fP=""
	Notification backend for scheduled runs (stdout|osascript).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-scheduler(1)\fP
