.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-status - Show last recorded machine repository state.


.SH SYNOPSIS
\fBbb status [flags]\fP


.SH DESCRIPTION
Show last recorded machine repository state.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status

.PP
\fB--include-catalog\fP=[]
	Limit scope to selected catalogs (repeatable).

.PP
\fB--json\fP[=false]
	Print machine and repository state as JSON.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP
