.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-scheduler-remove - Remove scheduler integration.


.SH SYNOPSIS
\fBbb scheduler remove [flags]\fP


.SH DESCRIPTION
Remove scheduler integration.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-scheduler(1)\fP
