.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-scheduler-status - Show scheduler installation status.


.SH SYNOPSIS
\fBbb scheduler status [flags]\fP


.SH DESCRIPTION
Show scheduler installation status.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-scheduler(1)\fP
