.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb-version - Print bb build version information.


.SH SYNOPSIS
\fBbb version [flags]\fP


.SH DESCRIPTION
Print bb build version information.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb(1)\fP
