.nh
.TH "BB" "1" "Feb 2026" "bb" ""

.SH NAME
bb - Keep Git repositories consistent across machines.


.SH SYNOPSIS
\fBbb [flags]\fP


.SH DESCRIPTION
bb is a local-first CLI for repository bootstrap and safe cross-machine convergence.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bb

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress verbose bb logs.


.SH SEE ALSO
\fBbb-catalog(1)\fP, \fBbb-clone(1)\fP, \fBbb-completion(1)\fP, \fBbb-config(1)\fP, \fBbb-doctor(1)\fP, \fBbb-ensure(1)\fP, \fBbb-fix(1)\fP, \fBbb-init(1)\fP, \fBbb-link(1)\fP, \fBbb-repo(1)\fP, \fBbb-scan(1)\fP, \fBbb-scheduler(1)\fP, \fBbb-status(1)\fP, \fBbb-sync(1)\fP
